apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-web
spec:
  replicas: 2
  selector:
    matchLabels:
      role: web-frontend
  template:
    metadata:
      labels:
        role: web-frontend
    spec:
      containers:
      - name: nfs-web
        image: nginx
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
            - name: volume-nfs
              mountPath: "/usr/share/nginx/html"
        ports:
          - name: web
            containerPort: 80
      restartPolicy: Always
      volumes:
      - name: volume-nfs
        persistentVolumeClaim:
          claimName: my-nfs-pvc
